# Generated by Django 3.1.1 on 2020-09-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='emp_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='manager_name',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
